### PR TITLE
restrict libs to link to Posix systems

### PR DESCRIPTION
**Pull request by ghost**
HIDAPI uses a dll under Windows.

Note 

1. I haven't tested it yet (I'm on the way to...). I suppose you hadn't either since it's likely that linking would fail for a program under Windows.
2. Tag required for DUB

### CODE REVIEW

**Comment by FFY00** [comment]
This is fine. I didn't test it as I don't use windows. As long as the linux build doesn't break I don't really care. If someone wants to get this working on Windows please send a patch.

Could you also remove `libs: hidapi` from `meson.build` in this patch? This prevents a `libs` key for being created again when meson runs.

**Comment by ghost** [comment]
That does not build but for other reasons. 

1. the source files specified in the dub json are not necessary. dub auto detects them. 
2. bunch of compilation errors

```
hidapi-d 1.0.3: building configuration "library"...
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(39,26): Error: function hidapi.bindings.hid_open(ushort vendor_id, ushort p
roduct_id, const(wchar)* serial_number) is not callable using argument types (usho
rt, ushort, immutable(dchar)*)
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(39,26):        cannot pass argument cast(immutable(dchar)*)cast(immutable(c
har)*)serial_number of type immutable(dchar)* to parameter const(wchar)* serial_nu
mber
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(192,42): Error: function hidapi.bindings.hid_get_manufacturer_string(hid_de
vice_* device, wchar* string, uint maxlen) is not callable using argument types (h
id_device_*, dchar*, uint)
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(192,42):        cannot pass argument cast(dchar*)buf of type dchar* to para
meter wchar* string
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(218,37): Error: function hidapi.bindings.hid_get_product_string(hid_device_
* device, wchar* string, uint maxlen) is not callable using argument types (hid_de
vice_*, dchar*, uint)
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(218,37):        cannot pass argument cast(dchar*)buf of type dchar* to para
meter wchar* string
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(244,43): Error: function hidapi.bindings.hid_get_serial_number_string(hid_d
evice_* device, wchar* string, uint maxlen) is not callable using argument types (
hid_device_*, dchar*, uint)
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(244,43):        cannot pass argument cast(dchar*)buf of type dchar* to para
meter wchar* string
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(274,37): Error: function hidapi.bindings.hid_get_indexed_string(hid_device_
* device, int string_index, wchar* string, uint maxlen) is not callable using argu
ment types (hid_device_*, uint, dchar*, uint)
C:\Users\abcde\AppData\Local\dub\packages\hidapi-d-1.0.3\hidapi-d\source\hidapi\de
vice.d(274,37):        cannot pass argument cast(dchar*)buf of type dchar* to para
meter wchar* string
C:\dev\dmd\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

But this PR is still valid. Maybe i'll try to see more in depth what's happening.

**Comment by FFY00** [comment]
The bindings probably need to be updated, I haven't touched them in a while.

**Comment by ghost** [comment]
I've anbandoned the project that used your library so I close for now. It was for linux only anyway, it's just that at some point I needed to verify something on win.

**Comment by FFY00** [comment]
I am going to update the bindings still. I was away without a PC and only came back today, that's why I didn't update them right away :grin:.

**Comment by FFY00** [comment]
Only documentation was updated in the new hidapi version. What version are you in?

**Comment by ghost** [comment]
I don't understand. I used latest tag of the D version. I used latest release of C version (which is not updated anymore since years I think). And I'm not on Win right now anyway.

**Comment by FFY00** [comment]
It all works perfectly here. This is probably a Windows thing :/

**Comment by ghost** [comment]
In you D API you would have to pass wide strings to the C API (for version(Windows)) and this would work under win ( + what should have done this PR)

**Pull request closed without merging**
